version: "3.9"
services:
  server:
    build: ./
    ports:
    - "5000:5000"
    volumes:
    - ./:/app
  web:
    build: ./quantum_solver_web
    ports:
    - "3000:3000"
    volumes:
    - ./quantum_solver_web:/usr/src/app
    depends_on:
      - server

