[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "numpy>=1.19.5",
  "matplotlib>=3.4.2",
  "qiskit>=0.19.1",
  "pwinput>=1.0.2",
  "halo">=0.0.31
]
build-backend = "setuptools.build_meta"
